FROM node:14

WORKDIR /home/app
COPY package*.json ./

# RUN npm install node-sass@4.14
RUN npm install

COPY Client/ ./Client/
COPY webpack.config.js ./
COPY .eslintrc ./


EXPOSE 9000

CMD [ "npm","run","serve:dev"]